const offerLink = "vnd.youtube://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbkNTLXVDalgxaERjSllkYk9WZjIwQU90TzB4Z3xBQ3Jtc0tsalppdUVQbTU3Ui1EWmZ1eGgycXBrd01fNERfWFREb3N5UFRHcmpITV92UTROby0ycEZKeW5ndEVmT3MtUXZIZlJHYmptaG1xYkxJYVZWWXY4MVAtbFFXT3lTQ2ZlUnBueDI3UllKUWpuOFVIdzZhcw&q=https%3A%2F%2Fopeninapp.co%2Fbnktm&html_redirect=1 ";

